### ISSUE TITLE
윤성님~

### ISSUE THREAD

**Issue by YWHyuk** [paranlee/paranlee.github.io#1]
안녕하세요 양원혁입니다:smile:
블로그 운영하고 계시고 있네요.. 멋집니다:thumbsup:

저도 github.io를 조금 사용하다가 글 쓰는 외적으로 너무 힘을 많이 써서 힘들더라구요.
그래서 wix 플랫폼에서 1년치 결제를 했는데, 역시나 그렇듯이 어떤 상호작용이 없으니까
글을 쓰는 재미가 떨어지더라구요..

윤성님은 제가 보기엔 저희 팀에서 열정이 가장 많은 분이기에 잘하실 것 같지만, 
혹시 저랑 같이 공동으로 블로그를 운영해보는 것에 대해 어떻게 생각하시나요?

플랫폼을 사용하면 운영하기도, 포스팅하기도 훨씬 쉽고, 서로 상호작용을 하면 
포스팅하는 것이 훨씬 재밌어지지 않을까 조심스레 생각해봅니다:smile:

**Comment by paranlee** [comment]
네 감사합니다 ㅎ 저두 공감하구 좋은 아이디어네요! 정리한 내용  포스팅하면서 피드백하면 좋을 것 같아요~

**Comment by YWHyuk** [comment]
자세한 내용은 카톡으로 논의해요~
카톡 아이디 kjhg4231 로 추가해주세요:smile:

**Comment by paranlee** [comment]
네~ 카톡 아이디 추가하려구 보니 검색이 안대네요 오잉😯
제 폰 번호로 추가해보시겠어요? olo-308l-9242
